eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl:
      defaultZone: http://localhost:10130/eureka/  #Eureka客户端与Eureka服务端进行交互的地址
server:
  port: 10150 #服务端口
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  application:
    name: gateway #指定服务名
  cloud:
    gateway:
      default-filters:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
